version: "3.9"

services:
  python-backend:
    build:
      context: ./backend/model
      dockerfile: Dockerfile
    container_name: python-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  go-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "8000:8000"
    depends_on:
      - python-backend   # รอ Python service พร้อมก่อน
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - python-backend
      - go-backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
